export const PLATFORM_SETTING_KEYS = {
  platformName: "platform.name",
  platformEmail: "platform.email",
  supportEmail: "platform.support_email",
  logoUrl: "platform.logo_url",
  currency: "platform.currency",
  timezone: "platform.timezone",
  dateFormat: "platform.date_format",
  defaultTrialDays: "subscription.default_trial_days",
  defaultGraceDays: "subscription.default_grace_days",
  maintenanceMode: "system.maintenance_mode",
  maintenanceMessage: "system.maintenance_message",
  termsUrl: "legal.terms_url",
  privacyUrl: "legal.privacy_url",
  sessionTimeout: "security.session_timeout_minutes",
  passwordMinLength: "security.password_min_length",
  adminAllowedIps: "security.admin_allowed_ips",
  adminRequire2fa: "security.admin_require_2fa",
} as const;
